<?xml version="1.0" encoding="utf-8"?><Database Name="VendaMais" Class="dcDadosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=JEFFERSON-PC\SQLEXPRESS;Initial Catalog=VendaMais;Integrated Security=True" SettingsObjectName="vdmNegocio.Properties.Settings" SettingsPropertyName="VendaMaisConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Categoria" Member="Categoria">
    <Type Name="Categoria">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nome" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Categoria_SubCategoriaDasCategorias" Member="SubCategoriaDasCategorias" ThisKey="id" OtherKey="id_categoria" Type="SubCategoriaDasCategorias" />
      <Association Name="Categoria_Produto" Member="Produto" ThisKey="id" OtherKey="id_categoria" Type="Produto" />
    </Type>
  </Table>
  <Table Name="dbo.Pessoa" Member="Pessoa">
    <Type Name="Pessoa">
      <Column Name="idPessoa" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Pessoa_PessoaFisica" Member="PessoaFisica" ThisKey="idPessoa" OtherKey="idPessoa" Type="PessoaFisica" Cardinality="One" />
      <Association Name="Pessoa_PessoaJuridica" Member="PessoaJuridica" ThisKey="idPessoa" OtherKey="idPessoa" Type="PessoaJuridica" Cardinality="One" />
      <Association Name="Pessoa_Usuario" Member="Usuario" ThisKey="idPessoa" OtherKey="IdPessoa" Type="Usuario" />
    </Type>
  </Table>
  <Table Name="dbo.PessoaFisica" Member="PessoaFisica">
    <Type Name="PessoaFisica">
      <Column Name="idPessoa" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NomeCompleto" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CPF" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="RG" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="Pessoa_PessoaFisica" Member="Pessoa" ThisKey="idPessoa" OtherKey="idPessoa" Type="Pessoa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PessoaJuridica" Member="PessoaJuridica">
    <Type Name="PessoaJuridica">
      <Column Name="idPessoa" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RazaoSocial" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CNPJ" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="Pessoa_PessoaJuridica" Member="Pessoa" ThisKey="idPessoa" OtherKey="idPessoa" Type="Pessoa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProdutoImagem" Member="ProdutoImagem">
    <Type Name="ProdutoImagem">
      <Column Name="id_imagem" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_produto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="caminho" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="Produto_ProdutoImagem" Member="Produto" ThisKey="id_produto" OtherKey="id_produto" Type="Produto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SubCategoria" Member="SubCategoria">
    <Type Name="SubCategoria">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nome" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="SubCategoria_SubCategoriaDasCategorias" Member="SubCategoriaDasCategorias" ThisKey="id" OtherKey="id_subcategoria" Type="SubCategoriaDasCategorias" />
      <Association Name="SubCategoria_Produto" Member="Produto" ThisKey="id" OtherKey="id_sub_categoria" Type="Produto" />
    </Type>
  </Table>
  <Table Name="dbo.SubCategoriaDasCategorias" Member="SubCategoriaDasCategorias">
    <Type Name="SubCategoriaDasCategorias">
      <Column Name="id_categoria" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_subcategoria" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Categoria_SubCategoriaDasCategorias" Member="Categoria" ThisKey="id_categoria" OtherKey="id" Type="Categoria" IsForeignKey="true" />
      <Association Name="SubCategoria_SubCategoriaDasCategorias" Member="SubCategoria" ThisKey="id_subcategoria" OtherKey="id" Type="SubCategoria" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Usuario" Member="Usuario">
    <Type Name="Usuario">
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdPessoa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Senha" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Pessoa_Usuario" Member="Pessoa" ThisKey="IdPessoa" OtherKey="idPessoa" Type="Pessoa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Notificacao" Member="Notificacao">
    <Type Name="Notificacao">
      <Column Name="idNotificacao" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Tipo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Titulo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Data" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Tipo_Notificacao" Member="Tipo1" ThisKey="Tipo" OtherKey="idTipo" Type="Tipo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tipo" Member="Tipo">
    <Type Name="Tipo">
      <Column Name="idTipo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Imagem" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Descricao" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Tipo_Notificacao" Member="Notificacao" ThisKey="idTipo" OtherKey="Tipo" Type="Notificacao" />
    </Type>
  </Table>
  <Table Name="dbo.Produto" Member="Produto">
    <Type Name="Produto">
      <Column Name="id_produto" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="codigo_referencia" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="nome" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="descricao" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="id_sub_categoria" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data_inclusao" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="id_categoria" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="preco" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="tipo_unidade" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Produto_ProdutoImagem" Member="ProdutoImagem" ThisKey="id_produto" OtherKey="id_produto" Type="ProdutoImagem" />
      <Association Name="Categoria_Produto" Member="Categoria" ThisKey="id_categoria" OtherKey="id" Type="Categoria" IsForeignKey="true" />
      <Association Name="SubCategoria_Produto" Member="SubCategoria" ThisKey="id_sub_categoria" OtherKey="id" Type="SubCategoria" IsForeignKey="true" />
      <Association Name="ProdutoTipoUnidade_Produto" Member="ProdutoTipoUnidade" ThisKey="tipo_unidade" OtherKey="id" Type="ProdutoTipoUnidade" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProdutoTipoUnidade" Member="ProdutoTipoUnidade">
    <Type Name="ProdutoTipoUnidade">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Descricao" Type="System.String" DbType="NChar(2) NOT NULL" CanBeNull="false" />
      <Association Name="ProdutoTipoUnidade_Produto" Member="Produto" ThisKey="id" OtherKey="tipo_unidade" Type="Produto" />
    </Type>
  </Table>
  <Table Name="dbo.País" Member="País">
    <Type Name="Paí">
      <Column Name="idPaís" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Brasil" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Argentina" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>